<?php
/** @package DbEca::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("AcaoMap.php");

/**
 * AcaoDAO provides object-oriented access to the tb_action table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package DbEca::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class AcaoDAO extends Phreezable
{
	/** @var int */
	public $IdAction;

	/** @var string */
	public $StrCodAction;

	/** @var string */
	public $StrNameAction;


	/**
	 * Returns a dataset of TbPayments objects with matching TbActionIdAction
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetActionTbPaymentss($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_tb_payments_tb_action1", $criteria);
	}


}
?>