<?php
/** @package DbEca::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("CidadeMap.php");

/**
 * CidadeDAO provides object-oriented access to the tb_city table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package DbEca::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class CidadeDAO extends Phreezable
{
	/** @var int */
	public $IdCity;

	/** @var string */
	public $StrNameCity;

	/** @var string */
	public $StrCodSiafiCity;

	/** @var int */
	public $TbStateIdState;


	/**
	 * Returns a dataset of TbPayments objects with matching TbCityIdCity
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetCityTbPaymentss($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_tb_payments_tb_city1", $criteria);
	}

	/**
	 * Returns the foreign object based on the value of TbStateIdState
	 * @return TbState
	 */
	public function GetStateTbState()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_tb_city_tb_state");
	}


}
?>