<?php
/** @package DbEca::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("EstadoMap.php");

/**
 * EstadoDAO provides object-oriented access to the tb_state table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package DbEca::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class EstadoDAO extends Phreezable
{
	/** @var int */
	public $IdState;

	/** @var string */
	public $StrUf;

	/** @var string */
	public $StrName;

	/** @var int */
	public $TbRegionIdRegion;


	/**
	 * Returns a dataset of TbCity objects with matching TbStateIdState
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetStateTbCitys($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_tb_city_tb_state", $criteria);
	}

	/**
	 * Returns the foreign object based on the value of TbRegionIdRegion
	 * @return TbRegion
	 */
	public function GetRegionTbRegion()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_tb_state_tb_region1");
	}


}
?>