<?php
/** @package DbEca::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("ProgramaMap.php");

/**
 * ProgramaDAO provides object-oriented access to the tb_program table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package DbEca::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class ProgramaDAO extends Phreezable
{
	/** @var int */
	public $IdProgram;

	/** @var string */
	public $StrCodProgram;

	/** @var string */
	public $StrNameProgram;


	/**
	 * Returns a dataset of TbPayments objects with matching TbProgramIdProgram
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetProgramTbPaymentss($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_tb_payments_tb_program1", $criteria);
	}


}
?>